# Generated by Django 5.1 on 2024-08-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
